Add the onOpen, onClose and onChalExpired callbacks
hCaptcha/react-hcaptcha pull request #112
Opened 2022-01-21 11:51 UTC by zoryana94

<img width="1440" alt="Знімок екрана 2022-01-21 о 13 44 50" src="https://user-images.githubusercontent.com/21179657/150522430-55289c4a-9144-48aa-92c9-c87c16f1c325.png">
<img width="1440" alt="Знімок екрана 2022-01-21 о 13 15 42" src="https://user-images.githubusercontent.com/21179657/150522450-8d523fd4-7244-42e6-99a6-cdf769d1ea43.png">

2022-01-21 13:01 UTC, alidzm commented
Missing props declaration for the component. Let's add https://github.com/hCaptcha/react-hcaptcha/blob/master/types/index.d.ts

2022-01-21 14:25 UTC, wontem requested changes
The code looks good. Please also update `README.md` with the new callbacks

2022-01-21 14:33 UTC, wontem requested changes

2022-01-21 14:33 UTC, wontem commented on src/index.js
> +
Please also consider using `if (!isApiReady || isRemoved) return` in these callbacks.

2022-01-21 15:35 UTC, wontem reviewed
Looks good. @brdlyptrs please take a quick look since you probably have a better understanding of how these callbacks should work or maybe you aware of some edge cases

2022-01-21 22:35 UTC, brdlyptrs commented on src/index.js
> +      this.isCaptchaReady = this.isCaptchaReady.bind(this);
Can this be `isReady`?

2022-01-25 18:03 UTC, brdlyptrs commented
Last thing, can you bump the version, may be `1.1.0`?

2022-01-25 18:06 UTC, brdlyptrs approved these changes

2022-01-26 12:01 UTC, wontem approved these changes

2022-01-26 12:06 UTC, merged